### ISSUE TITLE
Same selection tool interaction for diagram nodes and edges

### ISSUE THREAD

**Issue by amivanoff** [agentlab/rdf4j-workspace#23]
* **Exactly the same** selection visual markers for selected Nodes and Edges. Same size, same colour.
* The same selection markers behavior (or interactivity):
  * Markers should appear after single click on edge, not on hover. Like nodes selection.
  * Selected edge should stay selected untl "click outside" (like node).

**Comment by Mvwivs** [comment]
Branch `issue-23-selection-consistency`.
Selection has same markers style and behavior. The only problem is: 
 - X6 node selection uses div elements with 10px size for markers, this means zooming doesn't change marker visual size
 - Current edge selection implementation uses x6 edge tool that renders svg circle, making it have the same resizing behavior is impossible (?). Alternative solution is to try using `EdgeView` (to render div)
