### ISSUE TITLE
Inflexible graph state management

### ISSUE THREAD

**Issue by amivanoff** [agentlab/rdf4j-workspace#3]

**Comment by Mvwivs** [comment]
In general consider localizing stores and components for easier maintenance and better flexibility/extensibility.

1. Classes are not allowed, consider using functions like `useLocalObservable` for `GraphStore` and `LayoutStore`. ([current code](https://github.com/agentlab/rdf4j-workspace/blob/6b8ce0087edc82f76c53a337557a109ae467af44/src/stores/graph/GraphStore.ts#L3)).
2. Global state is bad for flexibility ([current code](https://github.com/agentlab/rdf4j-workspace/blob/6b8ce0087edc82f76c53a337557a109ae467af44/src/stores/graph/index.ts#L55)). Consider using context providers to localize state. Project currently "has" 2 parts: user code (`Graph`) and reusable core (`Canvas`, ...), if state is global, it's impossible to create 2 __graphs__ (2 `Canvas` components from user perspective) at the same time in application.
3. Consider implementing `minimap` as React component. This would allow to incapsulate all `refs` and allow user to explicitly specify minimap (See `Stencil` component in `class_diagram` branch. On the other hand there are some problems with such approach: how `Canvas` can differentiate between stencil and graph nodes and render stencil, for example, on the right side. So this point is open for discussion).
4. `isClassDiagram` should not be [stored](https://github.com/agentlab/rdf4j-workspace/blob/6b8ce0087edc82f76c53a337557a109ae467af44/src/stores/graph/LayoutStore.ts#L9) inside `LayoutStore`. The only purpose of this store is size and position calculation.  Consider implementing `isClassDiagram` (and full "view kind" selection from list in the future) as separate store/state.
5. Consider moving [grid options](https://github.com/agentlab/rdf4j-workspace/blob/6b8ce0087edc82f76c53a337557a109ae467af44/src/stores/graph/LayoutStore.ts#L10) into separate store.  The only purpose of `LayoutStore` is size and position calculation.
